myTuple = (1,4,3,2,5,2)
myTuple1 = (1,2,6,9,8,7)
print(myTuple + myTuple1)
print(myTuple * 4)
print(myTuple.count(2))
print(myTuple.index(4))
print(len(myTuple))
print(max(myTuple))
print(min(myTuple))
print(tuple([1,2,3,4]))
